# Compiler: Use gcc or clang
CC = gcc
# C Flags: Warning levels, Optimization (optional), Debug symbols
CFLAGS = -Wall -Wextra -g
# Linker Flags: Need Flex library (-lfl), Math library (-lm) if needed
LDFLAGS = -lfl -lm

# Source directory
SRC_DIR = src
# Output directory for generated Python files (and compiler executable)
OUT_DIR = output
# Compiler executable name
TARGET = $(OUT_DIR)/wizuallc

# Bison/Flex generated files
BISON_C = $(SRC_DIR)/wizuall.tab.c
BISON_H = $(SRC_DIR)/wizuall.tab.h
FLEX_C = $(SRC_DIR)/lex.yy.c

# Compiler source files
C_SOURCES = $(SRC_DIR)/main.c $(BISON_C) $(FLEX_C) $(SRC_DIR)/symtab.c $(SRC_DIR)/codegen.c
# Compiler object files
OBJ = $(C_SOURCES:.c=.o)

# Default target
all: $(TARGET)

# Link the compiler executable
$(TARGET): $(OBJ)
	@mkdir -p $(OUT_DIR) # Ensure output directory exists
	$(CC) $(CFLAGS) $^ -o $@ $(LDFLAGS)
	@echo "Compiler executable created: $(TARGET)"

# Compile C source files to object files
$(SRC_DIR)/%.o: $(SRC_DIR)/%.c $(BISON_H) $(SRC_DIR)/symtab.h $(SRC_DIR)/codegen.h
	$(CC) $(CFLAGS) -c $< -o $@

# Rule for Bison generated C file (depends on .y and potentially headers it includes)
$(BISON_C): $(SRC_DIR)/wizuall.y $(SRC_DIR)/symtab.h $(SRC_DIR)/codegen.h
	bison -d -o $@ $(SRC_DIR)/wizuall.y

# Rule for Flex generated C file (depends on .l and the Bison header)
$(FLEX_C): $(SRC_DIR)/wizuall.l $(BISON_H)
	flex -o $@ $(SRC_DIR)/wizuall.l

# Explicit dependency for the header file generated by Bison
$(BISON_H): $(BISON_C)

# Rule to run compiler on example files
examples: $(TARGET) examples/simple_plot.wiz 
	@echo "Running compiler on examples..."
	$(TARGET) examples/simple_plot.wiz $(OUT_DIR)/simple_plot.py
	@echo "Generated Python files in $(OUT_DIR)/"
	@echo "Run them using: python $(OUT_DIR)/simple_plot.py"
	# @echo "Run them using: python $(OUT_DIR)/clustering.py (requires numpy, matplotlib, scikit-learn)"


# Phony targets
.PHONY: all clean examples

# Clean up generated files
clean:
	rm -f $(TARGET) $(OBJ) $(BISON_C) $(BISON_H) $(FLEX_C)
	rm -f $(OUT_DIR)/*.py
	@echo "Cleaned up generated files."